### ISSUE TITLE
TokenHandleStore uses wrong lifetime

### ISSUE THREAD

**Issue by bacobart** [rms81/IdentityServer3.Contrib.Nhibernate#1]
Hi,

FYI

Line:
https://github.com/rms81/IdentityServer3.Contrib.Nhibernate/blob/master/src/Core.Nhibernate/Stores/TokenHandleStore.cs#L52

Should be:

Expiry = DateTime.UtcNow.AddSeconds(value.Lifetime)

(see https://github.com/IdentityServer/IdentityServer3.EntityFramework/blob/master/Source/Core.EntityFramework/Stores/TokenHandleStore.cs#L43 )

**Comment by bacobart** [comment]
:)

**Comment by rms81** [comment]
> :)

It was a very difficult one. It took 2 years to find a solution. :)
Anyway. Thks
